<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Core" />
    <PackageReference Include="Framework" />
    <PackageReference Include="IntegrationEvents" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.Postgresql" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FileService.Contracts\FileService.Contracts.csproj" />
    <ProjectReference Include="..\FileService.Domain\FileService.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="HttpCommunication\" />
  </ItemGroup>
</Project>
