import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import AppSideBar from "@/components/sidebar/app.sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}
      >
        <SidebarProvider>
          <div className="flex h-screen w-full">
            <AppSideBar />
            <div className="flex-1 flex flex-col min-w-0">
              <Header />
              <main className="flex-1 overflow-auto p-10">{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
