services:
  education-content-service:
    container_name: education-content-service
    build:
      context: ./backend/EducationContentService
      dockerfile: Dockerfile
      args:
        NUGET_USERNAME: $NUGET_USERNAME
        NUGET_PASSWORD: $NUGET_PASSWORD
    ports:
      - "9006:9001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:9001
    restart: always

  file-service:
    container_name: file-service
    build:
      context: ./backend/FileService
      dockerfile: Dockerfile
      args:
        NUGET_USERNAME: $NUGET_USERNAME
        NUGET_PASSWORD: $NUGET_PASSWORD
    ports:
      - "9005:8090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8090
    restart: always
    depends_on:
      - postgres-file-service
      - minio-dev
      - seq
      - rabbitmq

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "5342:5341" # HTTP API and UI
      - "8081:80" # Optional: if you want to expose Seq on port 80 directly
    environment:
      ACCEPT_EULA: "Y" # Required to accept the Seq End User License Agreement
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    restart: always

  postgres-education-service:
    container_name: postgres-education-service
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: education-service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-file-service:
    container_name: postgres-file-service
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: file-service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-dev:
    container_name: minio-dev
    image: minio/minio:latest
    ports:
      - "9003:9000"
      - "9004:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    restart: always

  rabbitmq:
    image: rabbitmq:4.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

volumes:
  rabbitmq_data:
