<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\EducationContentService.Contracts\EducationContentService.Contracts.csproj" />
    <ProjectReference Include="..\EducationContentService.Domain\EducationContentService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Core" />
    <PackageReference Include="FileService.Contracts" />
    <PackageReference Include="Framework" />
    <PackageReference Include="IntegrationEvents" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.Postgresql" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>

