// <auto-generated />
using System;
using FileService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(FileServiceDbContext))]
    [Migration("20260404200430_AddMediaAssetOwner")]
    partial class AddMediaAssetOwner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .HasColumnType("jsonb")
                        .HasColumnName("key");

                    b.Property<string>("RawKey")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("media_assets", "public");

                    b.HasDiscriminator<string>("AssetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.MediaProcessing.VideoProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsCriticalError")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_video_processing_status");

                    b.HasIndex("Status", "StartedAt")
                        .HasDatabaseName("ix_video_processing_status_started_at");

                    b.ToTable("video_processing", "public");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("wolverine_incoming_envelopes", "public", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.ToTable("wolverine_outgoing_envelopes", "public", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("FileService.Domain.Assets.PreviewAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("PREVIEW");
                });

            modelBuilder.Entity("FileService.Domain.Assets.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Assets.MediaAsset");

                    b.HasDiscriminator().HasValue("VIDEO");
                });

            modelBuilder.Entity("FileService.Domain.Assets.MediaAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ExpectedChunksCount")
                                .HasColumnType("integer")
                                .HasColumnName("expected_chunks_count");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint")
                                .HasColumnName("size");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets", "public");

                            b1.ToJson("media_data");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("category");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasColumnType("text")
                                        .HasColumnName("value");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Extension")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("extension");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("name");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .ValueGeneratedOnUpdateSometimes()
                                        .HasColumnType("text")
                                        .HasColumnName("value");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets", "public");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();
                        });

                    b.OwnsOne("FileService.Domain.MediaOwner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("context");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("entity_id");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets", "public");

                            b1.ToJson("owner");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.Navigation("MediaData")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();
                });

            modelBuilder.Entity("FileService.Domain.MediaProcessing.VideoProcess", b =>
                {
                    b.OwnsOne("FileService.Domain.VideoMetaData", "MetaData", b1 =>
                        {
                            b1.Property<Guid>("VideoProcessId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("interval")
                                .HasColumnName("duration");

                            b1.Property<int>("Height")
                                .HasColumnType("integer")
                                .HasColumnName("height");

                            b1.Property<int>("Width")
                                .HasColumnType("integer")
                                .HasColumnName("width");

                            b1.HasKey("VideoProcessId");

                            b1.ToTable("video_processing", "public");

                            b1.ToJson("meta_data");

                            b1.WithOwner()
                                .HasForeignKey("VideoProcessId");
                        });

                    b.OwnsMany("FileService.Domain.MediaProcessing.ProcessingStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("ErrorMessage")
                                .HasColumnType("text")
                                .HasColumnName("error_message");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<string>("ResultData")
                                .HasColumnType("jsonb")
                                .HasColumnName("result_data");

                            b1.Property<DateTime?>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("started_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");

                            b1.Property<string>("StepType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("step_type");

                            b1.Property<Guid>("VideoProcessingId")
                                .HasColumnType("uuid")
                                .HasColumnName("video_processing_id");

                            b1.Property<int>("Weight")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("Status")
                                .HasDatabaseName("ix_processing_steps_status");

                            b1.HasIndex("StepType")
                                .HasDatabaseName("ix_processing_steps_step_type");

                            b1.HasIndex("VideoProcessingId");

                            b1.ToTable("processing_steps", "public");

                            b1.WithOwner()
                                .HasForeignKey("VideoProcessingId");
                        });

                    b.Navigation("MetaData");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
