<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <PackageId>IntegrationEvents</PackageId>
    <Version>0.0.2</Version>
    <Authors>Manuilov Oleg</Authors>
    <PackageDescription>Shared integration events for messaging</PackageDescription>
    <RepositoryUrl>https://github.com/olegbonder/EducationContentService</RepositoryUrl>
  </PropertyGroup>
  
  <ItemGroup>
    <Folder Include="Education\" />
  </ItemGroup>

</Project>
